services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microservices_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  pizza_service:
    build:
      context: ./pizza_service
    container_name: pizza_service
    ports:
      - "8001:8001"
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    depends_on:
      - postgres
    volumes:
      - ./pizza_service:/app
    working_dir: /app

  order_service:
    build:
      context: ./order_service
    container_name: order_service
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./order_service:/app
    working_dir: /app
    depends_on:
      - pizza_service
      - redis

  drink_service:
    build:
      context: ./drink_service
    container_name: drink_service
    ports:
      - "8004:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./drink_service:/app
    working_dir: /app
    depends_on:
      - postgres
    env_file:
      - ./drink_service/.env

  customer_service:
    build:
      context: ./customer_service
    container_name: customer_service
    ports:
      - "8003:8003"
    depends_on:
      - postgres
    volumes:
      - ./customer_service:/app
    working_dir: /app


  event_service:
    build:
      context: ./event_service
    container_name: event_service
    command: python main.py
    depends_on:
      - redis
      - postgres
    volumes:
      - ./event_service:/app
    working_dir: /app

  notifier_service:
    build:
      context: ./notifier_service
    container_name: notifier_service
    command: python main.py
    depends_on:
      - redis
    volumes:
      - ./notifier_service:/app
    working_dir: /app

  auth_service:
    build:
      context: ./auth_service
    container_name: auth_service
    command: uvicorn main:app --host 0.0.0.0 --port 8002
    ports:
      - "8010:8002"
    volumes:
      - ./auth_service:/app
    working_dir: /app
    depends_on:
      - postgres

volumes:
  pgdata: